### PR TITLE
Bring all stac-spec schemas into this project

### PR DESCRIPTION
**Pull request by JamesOConnor**
This looks like a bigger change than it is - the idea behind this is:

1. The directory structures of the spec need to be preserved due to relative path references, so we should take them from the stac-spec project
2. We want to be able to test every version for every item type, so we need all the schemas here anyway.
3. We can't practically validate _every_ tagged version of the spec - people won't be using release candidates going forward anyway, so in my opinion it shouldn't be offered in the validator
4. We can use the examples included in the stac-spec project for testing

What I've done is copied in the schemas+examples from each tagged version (major/minor) of the stac-spec project and included it here.

### CODE REVIEW

**Comment by JamesOConnor** [comment]
Looking at files changed is way impractical here - I'd suggest pulling the branch and having a look

**Comment by jbants** [comment]
Great! Thanks for the PR

1. Agreed. This will make it easier. Although, we will still need to build the ref links for cases were users want to supply their own schemas for testing

2. 👍 

3. I think we may need to support RCs. If we want people to try new spec versions out and see what works and what doesn't work, we should allow them to validate the test versions as well. Maybe we can bundle non RC's with the tool and then use a remote ref to download RCs?

4. 👍

**Comment by JamesOConnor** [comment]
1. Is that for extensions? I guess they should have a version associated with them too - in which case we can build the reference within the StacValidate class. Should be straightforward, but for a different PR.

3. Yeah, I guess you're right about the leading release candidate - certainly shouldn't bother with the older ones however, right? I've included the v0.8.0-rc1 in this PR

**Comment by JamesOConnor** [comment]
Will bump this - any idea if anyone has implemented against any of the older release candidates?

**Comment by jbants** [comment]
1. Yea, most often the case. Earlier we were doing quick changes with the core, but that has mostly slowed down as the core becomes more solid.

2. Agreed.

**Comment by jonhealy1** [comment]
@jbants

**Comment by jbants** [comment]
@JamesOConnor, We closing this in prep for a 2.0.0 release (STAC 1.0.0). Thanks for the PR!

**Comment by JamesOConnor** [comment]
Nice one @jbants, looking forward to the next version :)

**Pull request closed without merging**
